name: Build and Test OrderService

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (OrderService module)
      run: mvn -B -f OrderService/pom.xml clean package

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./OrderService
        push: true
        tags: ghcr.io/sarvinp/orderservice:latest
        file: ./OrderService/Dockerfile

    - name: Run container and test
      run: |
        docker run -d --name orderservice -p 8080:8080 ghcr.io/sarvinp/orderservice:latest
        # wait for the app to start
        for i in {1..30}; do
          if curl -sSf http://localhost:8080/orders/test; then
            echo "Service is up"; exit 0;
          fi
          sleep 2
        done
        echo "Service did not start in time"
        exit 1
